### ISSUE TITLE
Change FAAS_REPOSITORY to FAAS_REGISTRY

### ISSUE THREAD

**Issue by lance** [boson-project/faas#154]
I think probably it makes sense as @rhuss suggested, to change `FAAS_REPOSITORY` to `FAAS_REGISTRY` since that's really what we are asking for anyway (terminology in this space is so messy).

A simple Quarkus project faas.yaml looks like this:

```yaml
name: quarkus
namespace: ""
runtime: quarkus
image: docker.io/lanceball/quarkus:latest
trigger: events
builder: default
builderMap:
  default: quay.io/boson/faas-quarkus-jvm-builder
  jvm: quay.io/boson/faas-quarkus-jvm-builder
  native: quay.io/boson/faas-quarkus-native-builder
```

Instead, I think the image property should just be `quarkus:latest` and that we should persist the `FAAS_REGISTRY` value in this file as well. 

/cc @boson-project/core
