### ISSUE TITLE
Allow user to set environment variables for a Function

### ISSUE THREAD

**Issue by matejvasek** [boson-project/faas#157]
For JVM Quarkus we are using https://github.com/fabric8io-images/run-java-sh

The script can be controlled by environment variables.
In particular `JAVA_DEBUG`, which can enable debugging.

This might be useful for debugging in general.

**Comment by matejvasek** [comment]
There could be `--env` flag like `kn` has.
In `faas.yaml` there would be section with envvar too:
```yaml
# ...
env:
  - name: JAVA_DEBUG
    value: 1
#...
```
WDYT @boson-project/core
